#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
from subprocess import Popen, PIPE
import sys
import shlex



################### bzrRev: uses bzr branch (if exists) information to 
# determine a unique revision number
def bzrRev():
    if os.path.exists(".git"):
       version_info = {}
       #os.system("bzr version-info --python> version.py")
       #subprocess.check_output(["git" "show -s --format='%%h %%ci' HEAD]")
       os.system("git show -s --format='%h %ci' HEAD > version.tmp")
       version_info['revision_id'] = open('version.tmp').read().strip()

       
       from string import Template
       
       fich = open("gitrev.h","w")
       
       template=Template("""/* This file was generated by the "bzrRev" function
 * in SConstruct      
 * You should not modify it manually, as it may be re-generated.

 */

#ifndef GITREV_H
#define GITREV_H

#define GIT_REVID   "$revision_id"


#endif /* GITREV_H */


""")
       fich.write(template.substitute(version_info))
    


bzrRev()