// This file has been generated by Py++.

#include "boost/python.hpp"

#include "boost/python/suite/indexing/vector_indexing_suite.hpp"

#include "/ibpc/rhea/saladin/Src/ptools/trunk/ptools.h"

#include "Pybindings/Atom.pypp.hpp"

#include "Pybindings/AtomSelection.pypp.hpp"

#include "Pybindings/AttractForceField.pypp.hpp"

#include "Pybindings/Coord3D.pypp.hpp"

#include "Pybindings/ForceField.pypp.hpp"

#include "Pybindings/Lbfgs.pypp.hpp"

#include "Pybindings/Rigidbody.pypp.hpp"

#include "Pybindings/_ptools_free_functions.pypp.hpp"

#include "Pybindings/vector_less_double_comma_std_scope_allocator_less_double_grate___grate_.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(_ptools){
    register_vector_less_double_comma_std_scope_allocator_less_double_grate___grate__class();

    register_Atom_class();

    register_AtomSelection_class();

    bp::implicitly_convertible< PTools::Rigidbody &, PTools::AtomSelection >();

    register_ForceField_class();

    register_AttractForceField_class();

    register_Coord3D_class();

    register_Lbfgs_class();

    bp::implicitly_convertible< PTools::ForceField &, PTools::Lbfgs >();

    register_Rigidbody_class();

    bp::implicitly_convertible< std::string, PTools::Rigidbody >();

    register_free_functions();
}

