// This file has been generated by Py++.

#ifndef _ptools_free_functions_hpp__pyplusplus_wrapper
#define _ptools_free_functions_hpp__pyplusplus_wrapper

void register_free_functions();

#endif//_ptools_free_functions_hpp__pyplusplus_wrapper
