// This file has been generated by Py++.

#include "boost/python.hpp"

#include "boost/python/suite/indexing/vector_indexing_suite.hpp"

#include "/people/cheetah/asaladin/Src/ptools/trunk/ptools.h"

#include "/people/cheetah/asaladin/Src/ptools/trunk/pairlist_dummy.h"

#include "Pybindings/Atom.pypp.hpp"

#include "Pybindings/AtomSelection.pypp.hpp"

#include "Pybindings/Attract2PairList.pypp.hpp"

#include "Pybindings/AttractForceField.pypp.hpp"

#include "Pybindings/AttractForceField2.pypp.hpp"

#include "Pybindings/AttractRigidbody.pypp.hpp"

#include "Pybindings/Coord3D.pypp.hpp"

#include "Pybindings/ForceField.pypp.hpp"

#include "Pybindings/Lbfgs.pypp.hpp"

#include "Pybindings/PairList.pypp.hpp"

#include "Pybindings/Rigidbody.pypp.hpp"

#include "Pybindings/Vdouble.pypp.hpp"

#include "Pybindings/_ptools_free_functions.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(_ptools){
    register_Vdouble_class();

    register_Atom_class();

    register_AtomSelection_class();

    bp::implicitly_convertible< PTools::Rigidbody &, PTools::AtomSelection >();

    register_ForceField_class();

    register_AttractForceField_class();

    register_AttractForceField2_class();

    register_Rigidbody_class();

    bp::implicitly_convertible< std::string, PTools::Rigidbody >();

    register_AttractRigidbody_class();

    bp::implicitly_convertible< PTools::Rigidbody const &, PTools::AttractRigidbody >();

    register_Coord3D_class();

    register_Lbfgs_class();

    bp::implicitly_convertible< PTools::ForceField &, PTools::Lbfgs >();

    register_Attract2PairList_class();

    register_PairList_class();

    register_free_functions();
}

