// This file has been generated by Py++.

#include "_ptools_free_functions.pypp.hpp"
#include "boost/python.hpp"
#include "/ibpc/rhea/saladin/Src/ptools/trunk/ptools.h"

namespace bp = boost::python;

void register_free_functions(){

    { //::PTools::AttractEuler
    
        typedef void ( *AttractEuler_function_type )( ::PTools::Rigidbody const &,::PTools::Rigidbody &,double,double,double );
        
        bp::def( 
            "AttractEuler"
            , AttractEuler_function_type( &::PTools::AttractEuler )
            , ( bp::arg("source"), bp::arg("dest"), bp::arg("phi"), bp::arg("ssi"), bp::arg("rot") ) );
    
    }

    { //::PTools::Rmsd
    
        typedef double ( *Rmsd_function_type )( ::PTools::AtomSelection const &,::PTools::AtomSelection const & );
        
        bp::def( 
            "Rmsd"
            , Rmsd_function_type( &::PTools::Rmsd )
            , ( bp::arg("atsel1"), bp::arg("atsel2") ) );
    
    }

}
