// This file has been generated by Py++.

#include "boost/python.hpp"

#include "boost/python/suite/indexing/vector_indexing_suite.hpp"

#include "ptools.h"

#include "Pybindings/Atom.pypp.hpp"

#include "Pybindings/AtomPair.pypp.hpp"

#include "Pybindings/AtomSelection.pypp.hpp"

#include "Pybindings/Atomproperty.pypp.hpp"

#include "Pybindings/Attract2PairList.pypp.hpp"

#include "Pybindings/AttractForceField1.pypp.hpp"

#include "Pybindings/AttractForceField2.pypp.hpp"

#include "Pybindings/AttractRigidbody.pypp.hpp"

#include "Pybindings/BaseAttractForceField.pypp.hpp"

#include "Pybindings/Coord3D.pypp.hpp"

#include "Pybindings/CoordsArray.pypp.hpp"

#include "Pybindings/ForceField.pypp.hpp"

#include "Pybindings/Lbfgs.pypp.hpp"

#include "Pybindings/Matrix.pypp.hpp"

#include "Pybindings/McopForceField.pypp.hpp"

#include "Pybindings/Mcoprigid.pypp.hpp"

#include "Pybindings/Model.pypp.hpp"

#include "Pybindings/Pdb.pypp.hpp"

#include "Pybindings/Region.pypp.hpp"

#include "Pybindings/Rigidbody.pypp.hpp"

#include "Pybindings/Screw.pypp.hpp"

#include "Pybindings/Surface.pypp.hpp"

#include "Pybindings/VCoord3D.pypp.hpp"

#include "Pybindings/Vdouble.pypp.hpp"

#include "Pybindings/Vuint.pypp.hpp"

#include "Pybindings/_ptools_free_functions.pypp.hpp"

#include "Pybindings/vector_less__std_scope_vector_less__double__grate___grate_.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(_ptools){
    register_Vuint_class();

    register_vector_less__std_scope_vector_less__double__grate___grate__class();

    register_Vdouble_class();

    register_VCoord3D_class();

    register_Matrix_class();

    register_Atomproperty_class();

    register_Atom_class();

    register_AtomPair_class();

    register_AtomSelection_class();

    bp::implicitly_convertible< PTools::Rigidbody &, PTools::AtomSelection >();

    register_Attract2PairList_class();

    register_ForceField_class();

    register_BaseAttractForceField_class();

    register_AttractForceField1_class();

    register_AttractForceField2_class();

    register_CoordsArray_class();

    register_Rigidbody_class();

    bp::implicitly_convertible< std::string, PTools::Rigidbody >();

    register_AttractRigidbody_class();

    bp::implicitly_convertible< PTools::Rigidbody const &, PTools::AttractRigidbody >();

    register_Coord3D_class();

    register_Lbfgs_class();

    bp::implicitly_convertible< PTools::ForceField &, PTools::Lbfgs >();

    register_McopForceField_class();

    register_Mcoprigid_class();

    register_Model_class();

    register_Pdb_class();

    bp::implicitly_convertible< std::string const &, PTools::Pdb >();

    register_Region_class();

    register_Screw_class();

    register_Surface_class();

    register_free_functions();
}

