// This file has been generated by Py++.

#ifndef Atomproperty_hpp__pyplusplus_wrapper
#define Atomproperty_hpp__pyplusplus_wrapper

void register_Atomproperty_class();

#endif//Atomproperty_hpp__pyplusplus_wrapper
