// This file has been generated by Py++.

#include "AtomSelection.pypp.hpp"
#include "boost/python.hpp"
#include "/people/cheetah/asaladin/Src/ptools/trunk/ptools.h"
#include "/people/cheetah/asaladin/Src/ptools/trunk/py_details.h"

namespace bp = boost::python;

void register_AtomSelection_class(){

    bp::class_< PTools::AtomSelection >( "AtomSelection" )    
        .def( bp::init< >() )    
        .def( bp::init< PTools::AtomSelection const & >(( bp::arg("oldsel") )) )    
        .def( bp::init< PTools::Rigidbody & >(( bp::arg("rigid") )) )    
        .def( 
            "AddAtomIndex"
            , &::PTools::AtomSelection::AddAtomIndex
            , ( bp::arg("i") ) )    
        .def( 
            "CopyAtom"
            , &::PTools::AtomSelection::CopyAtom
            , ( bp::arg("i") ) )    
        .def( 
            "CreateRigid"
            , &::PTools::AtomSelection::CreateRigid )    
        .def( 
            "SetRigid"
            , &::PTools::AtomSelection::SetRigid
            , ( bp::arg("rig") ) )    
        .def( 
            "Size"
            , &::PTools::AtomSelection::Size )    
        .def( 
            "__getitem__"
            , &::PTools::AtomSelection::operator[]
            , ( bp::arg("i") )
            , bp::return_internal_reference< 1 >() )    
        .def( bp::self & bp::self )    
        .def( bp::self | bp::self );

}
