// This file has been generated by Py++.

#include "boost/python.hpp"
#include "ptools.h"
#include "Attract2PairList.pypp.hpp"

namespace bp = boost::python;

void register_Attract2PairList_class(){

    bp::class_< PTools::Attract2PairList >( "Attract2PairList" )    
        .def( bp::init< PTools::AttractRigidbody const &, PTools::AttractRigidbody const &, dbl >(( bp::arg("receptor"), bp::arg("ligand"), bp::arg("cutoff") )) )    
        .def( bp::init< PTools::AttractRigidbody const &, PTools::AttractRigidbody const & >(( bp::arg("receptor"), bp::arg("ligand") )) )    
        .def( bp::init< >() )    
        .def( 
            "GetCutoff"
            , &::PTools::Attract2PairList::GetCutoff )    
        .def( 
            "Size"
            , &::PTools::Attract2PairList::Size )    
        .def( 
            "addPair"
            , &::PTools::Attract2PairList::addPair
            , ( bp::arg("ligand"), bp::arg("receptor"), bp::arg("pair") ) )    
        .def( 
            "__getitem__"
            , &::PTools::Attract2PairList::operator[]
            , ( bp::arg("i") ) )    
        .def( 
            "update"
            , &::PTools::Attract2PairList::update );

}
