// This file has been generated by Py++.

#include "Attract2PairList.pypp.hpp"
#include "boost/python.hpp"
#include "/people/cheetah/asaladin/Src/ptools/trunk/ptools.h"
#include "/people/cheetah/asaladin/Src/ptools/trunk/py_details.h"

namespace bp = boost::python;

void register_Attract2PairList_class(){

    bp::class_< PTools::T_PairList<PTools::AttractRigidbody> >( "Attract2PairList", bp::init< PTools::AttractRigidbody const &, PTools::AttractRigidbody const &, double >(( bp::arg("receptor"), bp::arg("ligand"), bp::arg("cutoff") )) )    
        .def( bp::init< PTools::AttractRigidbody const &, PTools::AttractRigidbody const & >(( bp::arg("receptor"), bp::arg("ligand") )) )    
        .def( 
            "GetCutoff"
            , &::PTools::T_PairList<PTools::AttractRigidbody>::GetCutoff )    
        .def( 
            "Size"
            , &::PTools::T_PairList<PTools::AttractRigidbody>::Size )    
        .def( 
            "addPair"
            , &::PTools::T_PairList<PTools::AttractRigidbody>::addPair
            , ( bp::arg("ligand"), bp::arg("receptor"), bp::arg("pair") ) )    
        .def( 
            "__getitem__"
            , &::PTools::T_PairList<PTools::AttractRigidbody>::operator[]
            , ( bp::arg("i") ) )    
        .def( 
            "update"
            , &::PTools::T_PairList<PTools::AttractRigidbody>::update )    
        .def_readwrite( "no_update", &PTools::T_PairList<PTools::AttractRigidbody>::no_update );

}
