// This file has been generated by Py++.

#ifndef AttractForceField2_hpp__pyplusplus_wrapper
#define AttractForceField2_hpp__pyplusplus_wrapper

void register_AttractForceField2_class();

#endif//AttractForceField2_hpp__pyplusplus_wrapper
