// This file has been generated by Py++.

#include "boost/python.hpp"
#include "ptools.h"
#include "AttractForceField1.pypp.hpp"

namespace bp = boost::python;

struct AttractForceField1_wrapper : PTools::AttractForceField1, bp::wrapper< PTools::AttractForceField1 > {

    AttractForceField1_wrapper(PTools::AttractForceField1 const & arg )
    : PTools::AttractForceField1( arg )
      , bp::wrapper< PTools::AttractForceField1 >(){
        // copy constructor
        
    }

    AttractForceField1_wrapper(::std::string paramsFileName, ::dbl cutoff )
    : PTools::AttractForceField1( paramsFileName, cutoff )
      , bp::wrapper< PTools::AttractForceField1 >(){
        // constructor
    
    }

    virtual ::dbl nonbon8_forces( ::PTools::AttractRigidbody & rec, ::PTools::AttractRigidbody & lig, ::PTools::Attract2PairList & pairlist, ::std::vector< PTools::Coord3D > & forcerec, ::std::vector< PTools::Coord3D > & forcelig, bool print=false ) {
        if( bp::override func_nonbon8_forces = this->get_override( "nonbon8_forces" ) )
            return func_nonbon8_forces( boost::ref(rec), boost::ref(lig), boost::ref(pairlist), boost::ref(forcerec), boost::ref(forcelig), print );
        else
            return this->PTools::AttractForceField1::nonbon8_forces( boost::ref(rec), boost::ref(lig), boost::ref(pairlist), boost::ref(forcerec), boost::ref(forcelig), print );
    }
    
    
    ::dbl default_nonbon8_forces( ::PTools::AttractRigidbody & rec, ::PTools::AttractRigidbody & lig, ::PTools::Attract2PairList & pairlist, ::std::vector< PTools::Coord3D > & forcerec, ::std::vector< PTools::Coord3D > & forcelig, bool print=false ) {
        return PTools::AttractForceField1::nonbon8_forces( boost::ref(rec), boost::ref(lig), boost::ref(pairlist), boost::ref(forcerec), boost::ref(forcelig), print );
    }

};

void register_AttractForceField1_class(){

    bp::class_< AttractForceField1_wrapper, bp::bases< PTools::BaseAttractForceField > >( "AttractForceField1", bp::init< std::string, dbl >(( bp::arg("paramsFileName"), bp::arg("cutoff") )) )    
        .def( 
            "InitParams"
            , &::PTools::AttractForceField1::InitParams
            , ( bp::arg("paramsFileName") ) )    
        .def( 
            "nonbon8_forces"
            , &::PTools::AttractForceField1::nonbon8_forces
            , &AttractForceField1_wrapper::default_nonbon8_forces
            , ( bp::arg("rec"), bp::arg("lig"), bp::arg("pairlist"), bp::arg("forcerec"), bp::arg("forcelig"), bp::arg("print")=(bool)(false) ) );

}
