// This file has been generated by Py++.

#ifndef Attract2PairList_hpp__pyplusplus_wrapper
#define Attract2PairList_hpp__pyplusplus_wrapper

void register_Attract2PairList_class();

#endif//Attract2PairList_hpp__pyplusplus_wrapper
