// This file has been generated by Py++.

#ifndef AttractForceField_hpp__pyplusplus_wrapper
#define AttractForceField_hpp__pyplusplus_wrapper

void register_AttractForceField_class();

#endif//AttractForceField_hpp__pyplusplus_wrapper
