// This file has been generated by Py++.

#include "boost/python.hpp"
#include "ptools.h"
#include "AttractForceField2.pypp.hpp"

namespace bp = boost::python;

struct AttractForceField2_wrapper : PTools::AttractForceField2, bp::wrapper< PTools::AttractForceField2 > {

    AttractForceField2_wrapper(PTools::AttractForceField2 const & arg )
    : PTools::AttractForceField2( arg )
      , bp::wrapper< PTools::AttractForceField2 >(){
        // copy constructor
        
    }

    AttractForceField2_wrapper(::std::string paramsFileName, ::dbl cutoff )
    : PTools::AttractForceField2( paramsFileName, cutoff )
      , bp::wrapper< PTools::AttractForceField2 >(){
        // constructor
    
    }

    virtual ::dbl nonbon8_forces( ::PTools::AttractRigidbody & rec, ::PTools::AttractRigidbody & lig, ::PTools::Attract2PairList & pairlist, ::std::vector< PTools::Coord3D > & forcerec, ::std::vector< PTools::Coord3D > & forcelig, bool print=false ) {
        if( bp::override func_nonbon8_forces = this->get_override( "nonbon8_forces" ) )
            return func_nonbon8_forces( boost::ref(rec), boost::ref(lig), boost::ref(pairlist), boost::ref(forcerec), boost::ref(forcelig), print );
        else
            return this->PTools::AttractForceField2::nonbon8_forces( boost::ref(rec), boost::ref(lig), boost::ref(pairlist), boost::ref(forcerec), boost::ref(forcelig), print );
    }
    
    
    ::dbl default_nonbon8_forces( ::PTools::AttractRigidbody & rec, ::PTools::AttractRigidbody & lig, ::PTools::Attract2PairList & pairlist, ::std::vector< PTools::Coord3D > & forcerec, ::std::vector< PTools::Coord3D > & forcelig, bool print=false ) {
        return PTools::AttractForceField2::nonbon8_forces( boost::ref(rec), boost::ref(lig), boost::ref(pairlist), boost::ref(forcerec), boost::ref(forcelig), print );
    }

};

void register_AttractForceField2_class(){

    bp::class_< AttractForceField2_wrapper, bp::bases< PTools::BaseAttractForceField > >( "AttractForceField2", bp::init< std::string, dbl >(( bp::arg("paramsFileName"), bp::arg("cutoff") )) )    
        .def( 
            "nonbon8_forces"
            , &::PTools::AttractForceField2::nonbon8_forces
            , &AttractForceField2_wrapper::default_nonbon8_forces
            , ( bp::arg("rec"), bp::arg("lig"), bp::arg("pairlist"), bp::arg("forcerec"), bp::arg("forcelig"), bp::arg("print")=(bool)(false) ) );

}
