// This file has been generated by Py++.

#ifndef AttractRigidbody_hpp__pyplusplus_wrapper
#define AttractRigidbody_hpp__pyplusplus_wrapper

void register_AttractRigidbody_class();

#endif//AttractRigidbody_hpp__pyplusplus_wrapper
