// This file has been generated by Py++.

#ifndef AttractForceField1_hpp__pyplusplus_wrapper
#define AttractForceField1_hpp__pyplusplus_wrapper

void register_AttractForceField1_class();

#endif//AttractForceField1_hpp__pyplusplus_wrapper
