// This file has been generated by Py++.

#ifndef BaseAttractForceField_hpp__pyplusplus_wrapper
#define BaseAttractForceField_hpp__pyplusplus_wrapper

void register_BaseAttractForceField_class();

#endif//BaseAttractForceField_hpp__pyplusplus_wrapper
