// This file has been generated by Py++.

#ifndef CoordsArray_hpp__pyplusplus_wrapper
#define CoordsArray_hpp__pyplusplus_wrapper

void register_CoordsArray_class();

#endif//CoordsArray_hpp__pyplusplus_wrapper
