// This file has been generated by Py++.

#include "Coord3D.pypp.hpp"
#include "boost/python.hpp"
#include "/people/cheetah/asaladin/Src/ptools/trunk/ptools.h"
#include "/people/cheetah/asaladin/Src/ptools/trunk/py_details.h"

namespace bp = boost::python;

void register_Coord3D_class(){

    { //::PTools::Coord3D
        typedef bp::class_< PTools::Coord3D > Coord3D_exposer_t;
        Coord3D_exposer_t Coord3D_exposer = Coord3D_exposer_t( "Coord3D" );
        bp::scope Coord3D_scope( Coord3D_exposer );
        Coord3D_exposer.def( bp::init< >() );
        Coord3D_exposer.def( bp::init< double, double, double >(( bp::arg("nx"), bp::arg("ny"), bp::arg("nz") )) );
        Coord3D_exposer.def( bp::init< PTools::Coord3D const & >(( bp::arg("old") )) );
        { //::PTools::Coord3D::Normalize
        
            typedef ::PTools::Coord3D & ( ::PTools::Coord3D::*Normalize_function_type )(  ) ;
            
            Coord3D_exposer.def( 
                "Normalize"
                , Normalize_function_type( &::PTools::Coord3D::Normalize )
                , bp::return_internal_reference< 1 >() );
        
        }
        { //::PTools::Coord3D::operator=
        
            typedef ::PTools::Coord3D & ( ::PTools::Coord3D::*assign_function_type )( ::PTools::Coord3D const & ) ;
            
            Coord3D_exposer.def( 
                "assign"
                , assign_function_type( &::PTools::Coord3D::operator= )
                , ( bp::arg("C") )
                , bp::return_self< >() );
        
        }
        Coord3D_exposer.def_readwrite( "x", &PTools::Coord3D::x );
        Coord3D_exposer.def_readwrite( "y", &PTools::Coord3D::y );
        Coord3D_exposer.def_readwrite( "z", &PTools::Coord3D::z );
        Coord3D_exposer.def( bp::other< double >() * bp::self );
        Coord3D_exposer.def( bp::self * bp::other< double >() );
        Coord3D_exposer.def( bp::self + bp::self );
        Coord3D_exposer.def( bp::self += bp::self );
        Coord3D_exposer.def( bp::self - bp::self );
        Coord3D_exposer.def( bp::self -= bp::self );
    }

}
