// This file has been generated by Py++.

#include "boost/python.hpp"
#include "ptools.h"
#include "Lbfgs.pypp.hpp"

namespace bp = boost::python;

void register_Lbfgs_class(){

    bp::class_< PTools::Lbfgs, boost::noncopyable >( "Lbfgs", bp::init< PTools::ForceField & >(( bp::arg("toMinim") )) )    
        .def( 
            "GetMinimizedVars"
            , &::PTools::Lbfgs::GetMinimizedVars )    
        .def( 
            "GetMinimizedVarsAtIter"
            , &::PTools::Lbfgs::GetMinimizedVarsAtIter
            , ( bp::arg("iter") ) )    
        .def( 
            "GetNumberIter"
            , &::PTools::Lbfgs::GetNumberIter )    
        .def( 
            "minimize"
            , &::PTools::Lbfgs::minimize
            , ( bp::arg("maxiter") ) );

}
