// This file has been generated by Py++.

#include "boost/python.hpp"
#include "ptools.h"
#include "Matrix.pypp.hpp"

namespace bp = boost::python;

void register_Matrix_class(){

    bp::class_< Array2D< double > >( "Matrix" )    
        .def( bp::init< >() )    
        .def( bp::init< int, int >(( bp::arg("row"), bp::arg("columns") )) )    
        .def( 
            "Print"
            , &::Array2D< double >::Print )    
        .def( 
            "detach"
            , &::Array2D< double >::detach );

}
