// This file has been generated by Py++.

#ifndef Mcoprigid_hpp__pyplusplus_wrapper
#define Mcoprigid_hpp__pyplusplus_wrapper

void register_Mcoprigid_class();

#endif//Mcoprigid_hpp__pyplusplus_wrapper
