// This file has been generated by Py++.

#ifndef McopForceField_hpp__pyplusplus_wrapper
#define McopForceField_hpp__pyplusplus_wrapper

void register_McopForceField_class();

#endif//McopForceField_hpp__pyplusplus_wrapper
