// This file has been generated by Py++.

#include "boost/python.hpp"
#include "ptools.h"
#include "Mcoprigid.pypp.hpp"

namespace bp = boost::python;

void register_Mcoprigid_class(){

    bp::class_< PTools::Mcoprigid >( "Mcoprigid" )    
        .def( bp::init< >() )    
        .def( 
            "AttractEulerRotate"
            , &::PTools::Mcoprigid::AttractEulerRotate
            , ( bp::arg("phi"), bp::arg("ssi"), bp::arg("rot") ) )    
        .def( 
            "PrintWeights"
            , &::PTools::Mcoprigid::PrintWeights )    
        .def( 
            "Translate"
            , &::PTools::Mcoprigid::Translate
            , ( bp::arg("c") ) )    
        .def( 
            "addEnsemble"
            , &::PTools::Mcoprigid::addEnsemble
            , ( bp::arg("reg") ) )    
        .def( 
            "getWeights"
            , &::PTools::Mcoprigid::getWeights )    
        .def( 
            "setMain"
            , &::PTools::Mcoprigid::setMain
            , ( bp::arg("main") ) );

}
