// This file has been generated by Py++.

#include "boost/python.hpp"
#include "ptools.h"
#include "Model.pypp.hpp"

namespace bp = boost::python;

void register_Model_class(){

    bp::class_< PTools::Model >( "Model" )    
        .def( 
            "ABrotate"
            , &::PTools::Model::ABrotate
            , ( bp::arg("A"), bp::arg("B"), bp::arg("theta") ) )    
        .def( 
            "AttractEulerRotate"
            , &::PTools::Model::AttractEulerRotate
            , ( bp::arg("phi"), bp::arg("ssi"), bp::arg("rot") ) )    
        .def( 
            "Translate"
            , &::PTools::Model::Translate
            , ( bp::arg("tr") ) )    
        .def( 
            "getHetatm"
            , &::PTools::Model::getHetatm )    
        .def( 
            "getMain"
            , &::PTools::Model::getMain );

}
