// This file has been generated by Py++.

#include "PairList.pypp.hpp"
#include "boost/python.hpp"
#include "/people/cheetah/asaladin/Src/ptools/trunk/ptools.h"
#include "/people/cheetah/asaladin/Src/ptools/trunk/py_details.h"

namespace bp = boost::python;

void register_PairList_class(){

    bp::class_< PTools::T_PairList<PTools::Rigidbody> >( "PairList", bp::init< PTools::Rigidbody const &, PTools::Rigidbody const &, double >(( bp::arg("receptor"), bp::arg("ligand"), bp::arg("cutoff") )) )    
        .def( bp::init< PTools::Rigidbody const &, PTools::Rigidbody const & >(( bp::arg("receptor"), bp::arg("ligand") )) )    
        .def( 
            "GetCutoff"
            , &::PTools::T_PairList<PTools::Rigidbody>::GetCutoff )    
        .def( 
            "Size"
            , &::PTools::T_PairList<PTools::Rigidbody>::Size )    
        .def( 
            "addPair"
            , &::PTools::T_PairList<PTools::Rigidbody>::addPair
            , ( bp::arg("ligand"), bp::arg("receptor"), bp::arg("pair") ) )    
        .def( 
            "__getitem__"
            , &::PTools::T_PairList<PTools::Rigidbody>::operator[]
            , ( bp::arg("i") ) )    
        .def( 
            "update"
            , &::PTools::T_PairList<PTools::Rigidbody>::update )    
        .def_readwrite( "no_update", &PTools::T_PairList<PTools::Rigidbody>::no_update );

}
