// This file has been generated by Py++.

#include "boost/python.hpp"
#include "ptools.h"
#include "Pdb.pypp.hpp"

namespace bp = boost::python;

void register_Pdb_class(){

    bp::class_< PTools::Pdb >( "Pdb", bp::init< std::string const & >(( bp::arg("pdbname") )) )    
        .def( 
            "nbmodels"
            , &::PTools::Pdb::nbmodels )    
        .def( 
            "__getitem__"
            , &::PTools::Pdb::operator[]
            , ( bp::arg("i") ) );

}
