// This file has been generated by Py++.

#include "boost/python.hpp"
#include "ptools.h"
#include "Region.pypp.hpp"

namespace bp = boost::python;

void register_Region_class(){

    bp::class_< PTools::Region >( "Region" )    
        .def( 
            "addCopy"
            , &::PTools::Region::addCopy
            , ( bp::arg("cop") ) )    
        .def( 
            "__getitem__"
            , &::PTools::Region::operator[]
            , ( bp::arg("i") )
            , bp::return_internal_reference< >() )    
        .def( 
            "size"
            , &::PTools::Region::size );

}
