// This file has been generated by Py++.

#ifndef Rigidbody_hpp__pyplusplus_wrapper
#define Rigidbody_hpp__pyplusplus_wrapper

void register_Rigidbody_class();

#endif//Rigidbody_hpp__pyplusplus_wrapper
