// This file has been generated by Py++.

#include "boost/python.hpp"
#include "ptools.h"
#include "Rigidbody.pypp.hpp"

namespace bp = boost::python;

struct Rigidbody_wrapper : PTools::Rigidbody, bp::wrapper< PTools::Rigidbody > {

    Rigidbody_wrapper( )
    : PTools::Rigidbody( )
      , bp::wrapper< PTools::Rigidbody >(){
        // null constructor
    
    }

    Rigidbody_wrapper(::std::string filename )
    : PTools::Rigidbody( filename )
      , bp::wrapper< PTools::Rigidbody >(){
        // constructor
    
    }

    Rigidbody_wrapper(::PTools::Rigidbody const & model )
    : PTools::Rigidbody( boost::ref(model) )
      , bp::wrapper< PTools::Rigidbody >(){
        // copy constructor
    
    }

    virtual ::PTools::Atom CopyAtom( ::uint i ) const  {
        if( bp::override func_CopyAtom = this->get_override( "CopyAtom" ) )
            return func_CopyAtom( i );
        else
            return this->PTools::Rigidbody::CopyAtom( i );
    }
    
    
    ::PTools::Atom default_CopyAtom( ::uint i ) const  {
        return PTools::Rigidbody::CopyAtom( i );
    }

    virtual bool isAtomActive( ::uint i ) const  {
        if( bp::override func_isAtomActive = this->get_override( "isAtomActive" ) )
            return func_isAtomActive( i );
        else
            return this->PTools::Rigidbody::isAtomActive( i );
    }
    
    
    bool default_isAtomActive( ::uint i ) const  {
        return PTools::Rigidbody::isAtomActive( i );
    }

};

void register_Rigidbody_class(){

    bp::class_< Rigidbody_wrapper >( "Rigidbody" )    
        .def( bp::init< >() )    
        .def( bp::init< std::string >(( bp::arg("filename") )) )    
        .def( bp::init< PTools::Rigidbody const & >(( bp::arg("model") )) )    
        .def( 
            "ABrotate"
            , &::PTools::Rigidbody::ABrotate
            , ( bp::arg("A"), bp::arg("B"), bp::arg("theta") ) )    
        .def( 
            "AddAtom"
            , (void ( ::PTools::Rigidbody::* )( ::PTools::Atomproperty const &,::PTools::Coord3D ) )( &::PTools::Rigidbody::AddAtom )
            , ( bp::arg("at"), bp::arg("co") ) )    
        .def( 
            "AddAtom"
            , (void ( ::PTools::Rigidbody::* )( ::PTools::Atom const & ) )( &::PTools::Rigidbody::AddAtom )
            , ( bp::arg("at") ) )    
        .def( 
            "AttractEulerRotate"
            , &::PTools::Rigidbody::AttractEulerRotate
            , ( bp::arg("phi"), bp::arg("ssi"), bp::arg("rot") ) )    
        .def( 
            "CA"
            , &::PTools::Rigidbody::CA )    
        .def( 
            "CenterToOrigin"
            , &::PTools::Rigidbody::CenterToOrigin )    
        .def( 
            "CopyAtom"
            , &::PTools::Rigidbody::CopyAtom
            , &Rigidbody_wrapper::default_CopyAtom
            , ( bp::arg("i") ) )    
        .def( 
            "FindCenter"
            , &::PTools::Rigidbody::FindCenter )    
        .def( 
            "GetAtomProperty"
            , &::PTools::Rigidbody::GetAtomProperty
            , ( bp::arg("pos") )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "GetCoords"
            , &::PTools::Rigidbody::GetCoords
            , ( bp::arg("i") ) )    
        .def( 
            "PrintPDB"
            , &::PTools::Rigidbody::PrintPDB )    
        .def( 
            "Radius"
            , &::PTools::Rigidbody::Radius )    
        .def( 
            "RadiusGyration"
            , &::PTools::Rigidbody::RadiusGyration )    
        .def( 
            "SelectAllAtoms"
            , &::PTools::Rigidbody::SelectAllAtoms )    
        .def( 
            "SelectAtomType"
            , &::PTools::Rigidbody::SelectAtomType
            , ( bp::arg("atomtype") ) )    
        .def( 
            "SelectChainId"
            , &::PTools::Rigidbody::SelectChainId
            , ( bp::arg("chainid") ) )    
        .def( 
            "SelectResRange"
            , &::PTools::Rigidbody::SelectResRange
            , ( bp::arg("start"), bp::arg("stop") ) )    
        .def( 
            "SelectResidType"
            , &::PTools::Rigidbody::SelectResidType
            , ( bp::arg("residtype") ) )    
        .def( 
            "Size"
            , &::PTools::Rigidbody::Size )    
        .def( 
            "Translate"
            , &::PTools::Rigidbody::Translate
            , ( bp::arg("tr") ) )    
        .def( 
            "getDescription"
            , &::PTools::Rigidbody::getDescription )    
        .def( 
            "isAtomActive"
            , &::PTools::Rigidbody::isAtomActive
            , &Rigidbody_wrapper::default_isAtomActive
            , ( bp::arg("i") ) )    
        .def( bp::self + bp::self )    
        .def( 
            "setDescription"
            , &::PTools::Rigidbody::setDescription
            , ( bp::arg("descr") ) );

}
