// This file has been generated by Py++.

#include "boost/python.hpp"
#include "ptools.h"
#include "Screw.pypp.hpp"

namespace bp = boost::python;

void register_Screw_class(){

    bp::class_< PTools::Screw >( "Screw" )    
        .def( 
            "Print"
            , &::PTools::Screw::print )    
        .def_readwrite( "angle", &PTools::Screw::angle )    
        .def_readwrite( "point", &PTools::Screw::point )    
        .def_readwrite( "transVector", &PTools::Screw::transVector );

}
