// This file has been generated by Py++.

#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
#include "ptools.h"
#include "VCoord3D.pypp.hpp"

namespace bp = boost::python;

void register_VCoord3D_class(){

    { //::std::vector< PTools::Coord3D >
        typedef bp::class_< std::vector< PTools::Coord3D > > VCoord3D_exposer_t;
        VCoord3D_exposer_t VCoord3D_exposer = VCoord3D_exposer_t( "VCoord3D" );
        bp::scope VCoord3D_scope( VCoord3D_exposer );
        VCoord3D_exposer.def( bp::vector_indexing_suite< ::std::vector< PTools::Coord3D > >() );
    }

}
