// This file has been generated by Py++.

#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
#include "ptools.h"
#include "Vdouble.pypp.hpp"

namespace bp = boost::python;

void register_Vdouble_class(){

    { //::std::vector< double >
        typedef bp::class_< std::vector< double > > Vdouble_exposer_t;
        Vdouble_exposer_t Vdouble_exposer = Vdouble_exposer_t( "Vdouble" );
        bp::scope Vdouble_scope( Vdouble_exposer );
        Vdouble_exposer.def( bp::vector_indexing_suite< ::std::vector< double >, true >() );
    }

}
