// This file has been generated by Py++.

#include "Vuint.pypp.hpp"
#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
#include "/people/cheetah/asaladin/Src/ptools/trunk/ptools.h"
#include "/people/cheetah/asaladin/Src/ptools/trunk/py_details.h"

namespace bp = boost::python;

void register_Vuint_class(){

    { //::std::vector<unsigned, std::allocator<unsigned> >
        typedef bp::class_< std::vector<unsigned, std::allocator<unsigned> > > Vuint_exposer_t;
        Vuint_exposer_t Vuint_exposer = Vuint_exposer_t( "Vuint" );
        bp::scope Vuint_scope( Vuint_exposer );
        Vuint_exposer.def( bp::vector_indexing_suite< ::std::vector<unsigned, std::allocator<unsigned> >, true >() );
    }

}
