// This file has been generated by Py++.

#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
#include "ptools.h"
#include "Vuint.pypp.hpp"

namespace bp = boost::python;

void register_Vuint_class(){

    { //::std::vector< unsigned int >
        typedef bp::class_< std::vector< unsigned int > > Vuint_exposer_t;
        Vuint_exposer_t Vuint_exposer = Vuint_exposer_t( "Vuint" );
        bp::scope Vuint_scope( Vuint_exposer );
        Vuint_exposer.def( bp::vector_indexing_suite< ::std::vector< unsigned int >, true >() );
    }

}
